local mod = get_mod("VersusMode")

return {
    name = mod:localize("mod_name"),
    description = mod:localize("mod_description"),
    is_togglable = true,
    options = {
        widgets = {
            {
                setting_id = "match_setup_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "enable_versus_mode",
                        type = "checkbox",
                        default_value = true,
                        tooltip = "enable_versus_mode_tooltip",
                    },
                    {
                        setting_id = "enable_versus_roster_menu",
                        type = "checkbox",
                        default_value = true,
                        tooltip = "enable_versus_roster_menu_tooltip",
                    },
                    {
                        setting_id = "infected_menu_keybind",
                        type = "keybind",
                        default_value = {},
                        keybind_trigger = "held",
                        keybind_type = "function_call",
                        function_name = "toggle_versus_roster_menu",
                    },
                    {
                        setting_id = "infected_menu_keybind_hold",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "hold_to_activate_tooltip",
                    },
                },
            },
            {
                setting_id = "respawn_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "enable_automatic_respawn",
                        type = "checkbox",
                        default_value = true,
                        tooltip = "enable_automatic_respawn_tooltip",
                    },
                    {
                        setting_id = "enable_random_safe_spawn",
                        type = "checkbox",
                        default_value = true,
                        tooltip = "enable_random_safe_spawn_tooltip",
                    },
                    {
                        setting_id = "infected_respawn_delay",
                        type = "numeric",
                        default_value = 10,
                        range = { 0, 60 },
                        decimals_number = 0,
                        step_size_value = 1,
                        tooltip = "infected_respawn_delay_tooltip",
                    },
                    {
                        setting_id = "infected_min_spawn_distance",
                        type = "numeric",
                        default_value = 5,
                        range = { 5, 50 },
                        decimals_number = 0,
                        step_size_value = 1,
                        tooltip = "infected_min_spawn_distance_tooltip",
                    },
                    {
                        setting_id = "enable_infected_spawn_selection",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "enable_infected_spawn_selection_tooltip",
                    },
                    {
                        setting_id = "cycle_infected_spawn_keybind",
                        type = "keybind",
                        default_value = {},
                        keybind_trigger = "held",
                        keybind_type = "function_call",
                        function_name = "cycle_infected_spawn",
                    },
                    {
                        setting_id = "cycle_infected_spawn_keybind_hold",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "hold_to_activate_tooltip",
                    },
                },
            },
            {
                setting_id = "health_rules_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "controlled_boss_health_multiplier",
                        type = "numeric",
                        default_value = 2,
                        range = { 1, 4 },
                        decimals_number = 1,
                        step_size_value = 0.1,
                        tooltip = "controlled_boss_health_multiplier_tooltip",
                    },
                    {
                        setting_id = "controlled_specialist_health_multiplier",
                        type = "numeric",
                        default_value = 1.5,
                        range = { 1, 4 },
                        decimals_number = 1,
                        step_size_value = 0.1,
                        tooltip = "controlled_specialist_health_multiplier_tooltip",
                    },
                    {
                        setting_id = "controlled_elite_health_multiplier",
                        type = "numeric",
                        default_value = 1.5,
                        range = { 1, 4 },
                        decimals_number = 1,
                        step_size_value = 0.1,
                        tooltip = "controlled_elite_health_multiplier_tooltip",
                    },
                },
            },
            {
                setting_id = "boss_rules_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "auto_takeover_normal_bosses",
                        type = "checkbox",
                        default_value = true,
                        tooltip = "auto_takeover_normal_bosses_tooltip",
                    },
                    {
                        setting_id = "max_infected_controlled_bosses",
                        type = "numeric",
                        default_value = 1,
                        range = { 1, 4 },
                        decimals_number = 0,
                        step_size_value = 1,
                        tooltip = "max_infected_controlled_bosses_tooltip",
                    },
                    {
                        setting_id = "controlled_boss_cc_effect_percent",
                        type = "numeric",
                        default_value = 50,
                        range = { 0, 100 },
                        decimals_number = 0,
                        step_size_value = 5,
                        tooltip = "controlled_boss_cc_effect_percent_tooltip",
                    },
                },
            },
            {
                setting_id = "controls_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "use_custom_enemy_keybinds",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "use_custom_enemy_keybinds_tooltip",
                    },
                    {
                        setting_id = "possess_keybind",
                        type = "keybind",
                        default_value = {},
                        keybind_trigger = "held",
                        keybind_type = "function_call",
                        function_name = "toggle_possession",
                    },
                    {
                        setting_id = "possess_keybind_hold",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "hold_to_activate_tooltip",
                    },
                    {
                        setting_id = "long_hold_threshold",
                        type = "numeric",
                        default_value = 0.45,
                        range = { 0.2, 1.5 },
                        decimals_number = 2,
                        step_size_value = 0.05,
                    },
                },
            },
            {
                setting_id = "custom_bindings_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "attack_keybind",
                        type = "keybind",
                        default_value = {},
                        keybind_trigger = "held",
                        keybind_type = "function_call",
                        function_name = "primary_attack",
                    },
                    {
                        setting_id = "attack_keybind_hold",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "hold_to_activate_tooltip",
                    },
                    {
                        setting_id = "heavy_attack_keybind",
                        type = "keybind",
                        default_value = {},
                        keybind_trigger = "held",
                        keybind_type = "function_call",
                        function_name = "heavy_attack",
                    },
                    {
                        setting_id = "heavy_attack_keybind_hold",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "hold_to_activate_tooltip",
                    },
                    {
                        setting_id = "alternate_attack_keybind",
                        type = "keybind",
                        default_value = {},
                        keybind_trigger = "held",
                        keybind_type = "function_call",
                        function_name = "alternate_attack",
                    },
                    {
                        setting_id = "alternate_attack_keybind_hold",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "hold_to_activate_tooltip",
                    },
                    {
                        setting_id = "special_attack_keybind",
                        type = "keybind",
                        default_value = {},
                        keybind_trigger = "held",
                        keybind_type = "function_call",
                        function_name = "special_attack",
                    },
                    {
                        setting_id = "special_attack_keybind_hold",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "hold_to_activate_tooltip",
                    },
                    {
                        setting_id = "cancel_action_keybind",
                        type = "keybind",
                        default_value = {},
                        keybind_trigger = "held",
                        keybind_type = "function_call",
                        function_name = "cancel_action",
                    },
                    {
                        setting_id = "cancel_action_keybind_hold",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "hold_to_activate_tooltip",
                    },
                    {
                        setting_id = "cycle_target_keybind",
                        type = "keybind",
                        default_value = {},
                        keybind_trigger = "held",
                        keybind_type = "function_call",
                        function_name = "cycle_target",
                    },
                    {
                        setting_id = "cycle_target_keybind_hold",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "hold_to_activate_tooltip",
                    },
                    {
                        setting_id = "target_lock_keybind",
                        type = "keybind",
                        default_value = {},
                        keybind_trigger = "held",
                        keybind_type = "function_call",
                        function_name = "toggle_target_lock",
                    },
                    {
                        setting_id = "target_lock_keybind_hold",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "hold_to_activate_tooltip",
                    },
                },
            },
            {
                setting_id = "control_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "selection_range",
                        type = "numeric",
                        default_value = 50,
                        range = { 10, 100 },
                        decimals_number = 0,
                        step_size_value = 5,
                    },
                    {
                        setting_id = "move_speed_percent",
                        type = "numeric",
                        default_value = 90,
                        range = { 25, 150 },
                        decimals_number = 0,
                        step_size_value = 5,
                    },
                    {
                        setting_id = "attack_burst_duration",
                        type = "numeric",
                        default_value = 2,
                        range = { 0.5, 5 },
                        decimals_number = 1,
                        step_size_value = 0.5,
                    },
                    {
                        setting_id = "attack_acquire_timeout",
                        type = "numeric",
                        default_value = 8,
                        range = { 2, 15 },
                        decimals_number = 1,
                        step_size_value = 0.5,
                    },
                    {
                        setting_id = "protect_player",
                        type = "checkbox",
                        default_value = true,
                    },
                    {
                        setting_id = "hound_heavy_trajectory_mode",
                        type = "dropdown",
                        default_value = "hold_charge",
                        options = {
                            {
                                text = "hound_trajectory_hold_charge",
                                value = "hold_charge",
                            },
                            {
                                text = "hound_trajectory_camera_pitch",
                                value = "camera_pitch",
                            },
                        },
                        tooltip = "hound_heavy_trajectory_mode_tooltip",
                    },
                    {
                        setting_id = "enable_mutant_throw_direction_adjustment",
                        type = "checkbox",
                        default_value = true,
                        tooltip = "enable_mutant_throw_direction_adjustment_tooltip",
                    },
                },
            },
            {
                setting_id = "camera_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "heretic_night_vision",
                        type = "checkbox",
                        default_value = true,
                        tooltip = "heretic_night_vision_tooltip",
                    },
                    {
                        setting_id = "heretic_night_vision_strength",
                        type = "numeric",
                        default_value = 3,
                        range = { 0, 5 },
                        decimals_number = 1,
                        step_size_value = 0.5,
                    },
                    {
                        setting_id = "mouse_sensitivity",
                        type = "numeric",
                        default_value = 100,
                        range = { 25, 300 },
                        decimals_number = 0,
                        step_size_value = 5,
                    },
                    {
                        setting_id = "camera_distance",
                        type = "numeric",
                        default_value = 7,
                        range = { 3, 14 },
                        decimals_number = 1,
                        step_size_value = 0.5,
                    },
                    {
                        setting_id = "camera_height",
                        type = "numeric",
                        default_value = 2.5,
                        range = { 1, 7 },
                        decimals_number = 1,
                        step_size_value = 0.5,
                    },
                    {
                        setting_id = "specialist_camera_distance",
                        type = "numeric",
                        default_value = 2,
                        range = { 0.5, 5 },
                        decimals_number = 2,
                        step_size_value = 0.05,
                        tooltip = "specialist_camera_distance_tooltip",
                    },
                    {
                        setting_id = "specialist_camera_horizontal_offset",
                        type = "numeric",
                        default_value = 0.4,
                        range = { -1.5, 1.5 },
                        decimals_number = 2,
                        step_size_value = 0.05,
                        tooltip = "specialist_camera_horizontal_offset_tooltip",
                    },
                    {
                        setting_id = "specialist_camera_height_adjustment",
                        type = "numeric",
                        default_value = 0,
                        range = { -1, 1 },
                        decimals_number = 2,
                        step_size_value = 0.05,
                        tooltip = "specialist_camera_height_adjustment_tooltip",
                    },
                    {
                        setting_id = "reset_camera_defaults",
                        type = "button",
                        button_text = "reset_camera_defaults_button",
                        button_trigger = "pressed",
                        function_name = "reset_camera_defaults",
                        tooltip = "reset_camera_defaults_tooltip",
                    },
                },
            },
            {
                setting_id = "sniper_scope_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "sniper_mouse_sensitivity_multiplier",
                        type = "numeric",
                        default_value = 100,
                        range = { 25, 200 },
                        decimals_number = 0,
                        step_size_value = 5,
                        tooltip = "sniper_mouse_sensitivity_multiplier_tooltip",
                    },
                    {
                        setting_id = "enable_sniper_scope_zoom",
                        type = "checkbox",
                        default_value = true,
                        tooltip = "enable_sniper_scope_zoom_tooltip",
                    },
                    {
                        setting_id = "sniper_scope_vertical_fov",
                        type = "numeric",
                        default_value = 35,
                        range = { 15, 60 },
                        decimals_number = 0,
                        step_size_value = 1,
                        tooltip = "sniper_scope_vertical_fov_tooltip",
                    },
                },
            },
            {
                setting_id = "hud_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "show_control_hud",
                        type = "checkbox",
                        default_value = true,
                    },
                    {
                        setting_id = "show_attack_log",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "show_attack_log_tooltip",
                    },
                    {
                        setting_id = "show_sniper_crosshair",
                        type = "checkbox",
                        default_value = false,
                    },
                    {
                        setting_id = "show_target_outline",
                        type = "checkbox",
                        default_value = true,
                        tooltip = "show_target_outline_tooltip",
                    },
                    {
                        setting_id = "show_allied_heretic_outlines",
                        type = "checkbox",
                        default_value = true,
                        tooltip = "show_allied_heretic_outlines_tooltip",
                    },
                    {
                        setting_id = "replace_player_panel",
                        type = "checkbox",
                        default_value = true,
                    },
                    {
                        setting_id = "hide_infected_team_panel",
                        type = "checkbox",
                        default_value = true,
                    },
                },
            },
            {
                setting_id = "hud_layout_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "enemy_panel_x",
                        type = "numeric",
                        default_value = 17,
                        range = { 0, 1850 },
                        decimals_number = 0,
                        step_size_value = 5,
                    },
                    {
                        setting_id = "enemy_panel_y",
                        type = "numeric",
                        default_value = -50,
                        range = { -500, 500 },
                        decimals_number = 0,
                        step_size_value = 5,
                    },
                    {
                        setting_id = "hud_x",
                        type = "numeric",
                        default_value = 40,
                        range = { 0, 1850 },
                        decimals_number = 0,
                        step_size_value = 10,
                    },
                    {
                        setting_id = "hud_y",
                        type = "numeric",
                        default_value = 210,
                        range = { 0, 1000 },
                        decimals_number = 0,
                        step_size_value = 10,
                    },
                    {
                        setting_id = "hud_font_size",
                        type = "numeric",
                        default_value = 18,
                        range = { 12, 30 },
                        decimals_number = 0,
                        step_size_value = 1,
                    },
                    {
                        setting_id = "hud_text_opacity",
                        type = "numeric",
                        default_value = 90,
                        range = { 20, 100 },
                        decimals_number = 0,
                        step_size_value = 5,
                    },
                    {
                        setting_id = "reset_hud_layout",
                        type = "button",
                        button_text = "reset_hud_layout_button",
                        button_trigger = "pressed",
                        function_name = "reset_hud_layout",
                        tooltip = "reset_hud_layout_tooltip",
                    },
                },
            },
            {
                setting_id = "experimental_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "default_first_person_view",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "default_first_person_view_tooltip",
                    },
                    {
                        setting_id = "toggle_first_person_view_keybind",
                        type = "keybind",
                        default_value = {},
                        keybind_trigger = "pressed",
                        keybind_type = "function_call",
                        function_name = "toggle_first_person_view",
                    },
                    {
                        setting_id = "enable_controlled_traversal",
                        type = "checkbox",
                        default_value = true,
                        tooltip = "enable_controlled_traversal_tooltip",
                    },
                    {
                        setting_id = "controlled_traverse_keybind",
                        type = "keybind",
                        default_value = {},
                        keybind_trigger = "pressed",
                        keybind_type = "function_call",
                        function_name = "controlled_context_action",
                    },
                    {
                        setting_id = "enable_last_survivor_buff",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "enable_last_survivor_buff_tooltip",
                    },
                    {
                        setting_id = "enable_specialist_variants",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "enable_specialist_variants_tooltip",
                    },
                    {
                        setting_id = "freeze_survivor_bots",
                        type = "checkbox",
                        default_value = false,
                        tooltip = "freeze_survivor_bots_tooltip",
                    },
                },
            },
        },
    },
}
