$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$repo = Split-Path $PSScriptRoot -Parent
$assetDir = Join-Path $repo 'assets/portraits'
$map = Get-Content -LiteralPath (Join-Path $assetDir 'map.json') -Raw | ConvertFrom-Json
$lua = [Text.StringBuilder]::new("-- Generated by tools/build-portraits.ps1 from supplied JPG portraits.`r`nlocal images = {}`r`n")
foreach ($entry in $map.PSObject.Properties) {
    $src = [Drawing.Image]::FromFile((Join-Path $assetDir $entry.Name))
    $width = 48
    $height = [int][Math]::Round($width * $src.Height / $src.Width)
    $bmp = [Drawing.Bitmap]::new($width, $height)
    $g = [Drawing.Graphics]::FromImage($bmp)
    $g.InterpolationMode = [Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $g.DrawImage($src, 0, 0, $width, $height)
    $g.Dispose(); $src.Dispose()
    $runs = [Collections.Generic.List[object]]::new()
    $previous = @{}
    for ($y = 0; $y -lt $height; $y++) {
        $current = @{}
        $row = @()
        for ($x = 0; $x -lt $width; $x++) {
            $c = $bmp.GetPixel($x, $y)
            $row += ,@([int]([Math]::Floor($c.R / 16) * 16 + 8), [int]([Math]::Floor($c.G / 16) * 16 + 8), [int]([Math]::Floor($c.B / 16) * 16 + 8))
        }
        $x = 0
        while ($x -lt $width) {
            $first = $x; $rgb = $row[$x]; $colorKey = $rgb -join ','
            do { $x++ } while ($x -lt $width -and ($row[$x] -join ',') -eq $colorKey)
            $key = "$first,$x,$colorKey"
            if ($previous.ContainsKey($key)) { $run = $previous[$key]; $run[3]++ }
            else { $run = @($first,$y,($x-$first),1,$rgb[0],$rgb[1],$rgb[2]); $runs.Add($run) }
            $current[$key] = $run
        }
        $previous = $current
    }
    $bmp.Dispose()
    # Seven bytes per rectangle, instead of one retained Lua table per rectangle.
    [void]$lua.Append("do local p = { width = $width, height = $height, packed = `"")
    foreach ($r in $runs) {
        foreach ($value in $r) {
            if ($value -lt 0 -or $value -gt 255) { throw 'Portrait field does not fit a byte' }
            [void]$lua.Append(('\{0:D3}' -f [int]$value))
        }
    }
    [void]$lua.Append("`" }`r`n")
    foreach ($breed in $entry.Value) { [void]$lua.Append("images.$breed = p`r`n") }
    [void]$lua.Append("end`r`n")
    Write-Output "$($entry.Name): $($runs.Count) rectangles"
}
[void]$lua.Append("return images`r`n")
[IO.File]::WriteAllText((Join-Path $repo 'scripts/mods/VersusMode/VersusMode_portrait_images.lua'), $lua.ToString(), [Text.UTF8Encoding]::new($false))
